#!groovy
pipeline {

  agent any

  tools {
    jdk 'jdk 8'
    maven 'mvn 3.8'
  }

  parameters {
    string(name: 'BRANCH', defaultValue: 'master', description: 'Branch to build')
  }

  environment {
    SERVICE_NAME = "provider-x"
    BRANCH_NAME = env.GIT_BRANCH.replace("origin/", "")
    PACT_URL = "http://localhost:9292"
    PACT_DOCKER_CLI = "--network host --rm pactfoundation/pact-cli:0.50.0.21 broker -b ${PACT_URL}"
    //PACT_FOLDER = env.WORKSPACE for real jenkins (non docker)
    PACT_FOLDER = env.WORKSPACE.replace("var", "/home/sonnd4/Documents/GitHub/infrastructure/jenkins")
    PACT_RETRY_OPTION = "--retry-while-unknown=4 --retry-interval=10"
  }

  stages {
    stage ('Build & Test') {
      steps {
          sh "mvn clean verify -Dpactbroker.consumerversionselectors.tags=SIT_ENV -Dpact.provider.version=${GIT_COMMIT} -Dpact.provider.tag=${BRANCH_NAME} -Dpact.verifier.publishResults=true"
      }
    }
    stage ('Get Latest SIT Version From Pact Broker') {
      steps {
        script {
          env.PROD_VERSION = sh(script: "sudo docker run ${PACT_DOCKER_CLI} describe-version -a ${SERVICE_NAME} -l SIT_ENV | tail -1 | cut -f 1 -d \\|", returnStdout: true).trim()
        }
        echo "Current prod version: " + PROD_VERSION
      }
    }
    stage('Can I deploy on SIT') {
      steps {
        script {
          //Tag the first pass contract as verified on SIT
          if (env.PROD_VERSION == 'Pacticipant version not found') {
            sh "sudo docker run ${PACT_DOCKER_CLI} create-version-tag -t SIT_ENV -a ${SERVICE_NAME} -e ${GIT_COMMIT}"
          }
        }
        sh "sudo docker run ${PACT_DOCKER_CLI} can-i-deploy -a ${SERVICE_NAME} -e ${GIT_COMMIT} --to SIT_ENV"
      }
    }
    stage('Mark as verified on SIT') {
      steps {
        sh "sudo docker run ${PACT_DOCKER_CLI} create-version-tag -a ${SERVICE_NAME} -e ${GIT_COMMIT} -t SIT_ENV"
      }
    }

    stage('Deploy on SIT') {
      when {
        expression { return env.BRANCH_NAME == 'master'; }
      }
      steps {
          sh "sudo docker run ${PACT_DOCKER_CLI} record-deployment --environment=SIT -a ${SERVICE_NAME} -e ${GIT_COMMIT}"
      }
    }
  }
}